language: ruby
rvm:
- 2.1

script: bundle exec jekyll build --drafts && bundle exec htmlproof ./_site
6	

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false   # enable travis run on container infrastructure
